name: DCDSM
channels:
  - pytorch
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.6.13
  - tensorflow=2.6.0  # TensorFlow
  - scikit-learn=0.24.2  # scikit-learn
  - matplotlib=3.3.4  # 用于绘图
  - pandas=1.1.5  # 数据处理
  - numpy=1.19.2  # 数值计算
  - pip
  - pip:
      - keras==2.6.0  # Keras